# docker-compose.yml
version: "3"

services:
  # MySQL database
  db:
    image: mariadb
    restart: unless-stopped
    container_name: wpp-plugin-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wpp-plugin-net

  wpp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: wpp-plugin-app
    environment:
      WORDPRESS_DB_HOST: wpp-plugin-db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      XDEBUG_HOST: host.docker.internal
      XDEBUG_IDEKEY: VSCODE
    volumes:
      - ./wp:/var/www/html
      - ./:/var/www/html/wp-content/plugins/wp-plugin-base
    ports:
      - 8080:80
    depends_on:
      - db 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - wpp-plugin-net

networks:
  wpp-plugin-net:

# Persist DB and WordPress data across containers
volumes:
  db-data:
  wp-data: